{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3417, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-f1961da6ff9c>\", line 1, in <module>\n",
      "    from white_box_cartoonizer.cartoonize import WB_Cartoonize\n",
      "  File \"/home/rajat/workspace/body/cartoonize/white_box_cartoonizer/cartoonize.py\", line 14, in <module>\n",
      "    import skvideo.io\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/skvideo/__init__.py\", line 3, in <module>\n",
      "    from .utils import check_output, where\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/skvideo/utils/__init__.py\", line 11, in <module>\n",
      "    from .stpyr import SpatialSteerablePyramid, rolling_window\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/skvideo/utils/stpyr.py\", line 3, in <module>\n",
      "    import scipy.signal\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/scipy/signal/__init__.py\", line 301, in <module>\n",
      "    from .filter_design import *\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/scipy/signal/filter_design.py\", line 18, in <module>\n",
      "    from scipy import special, optimize, fft as sp_fft\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/scipy/optimize/__init__.py\", line 389, in <module>\n",
      "    from .optimize import *\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/scipy/optimize/optimize.py\", line 40, in <module>\n",
      "    from scipy._lib._util import getargspec_no_self as _getargspec\n",
      "ImportError: cannot import name 'getargspec_no_self' from 'scipy._lib._util' (/home/rajat/workspace/body/lib/python3.7/site-packages/scipy/_lib/_util.py)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ImportError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/posixpath.py\", line 383, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3417, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-f1961da6ff9c>\", line 1, in <module>\n",
      "    from white_box_cartoonizer.cartoonize import WB_Cartoonize\n",
      "  File \"/home/rajat/workspace/body/cartoonize/white_box_cartoonizer/cartoonize.py\", line 14, in <module>\n",
      "    import skvideo.io\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/skvideo/__init__.py\", line 3, in <module>\n",
      "    from .utils import check_output, where\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/skvideo/utils/__init__.py\", line 11, in <module>\n",
      "    from .stpyr import SpatialSteerablePyramid, rolling_window\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/skvideo/utils/stpyr.py\", line 3, in <module>\n",
      "    import scipy.signal\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/scipy/signal/__init__.py\", line 301, in <module>\n",
      "    from .filter_design import *\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/scipy/signal/filter_design.py\", line 18, in <module>\n",
      "    from scipy import special, optimize, fft as sp_fft\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/scipy/optimize/__init__.py\", line 389, in <module>\n",
      "    from .optimize import *\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/scipy/optimize/optimize.py\", line 40, in <module>\n",
      "    from scipy._lib._util import getargspec_no_self as _getargspec\n",
      "ImportError: cannot import name 'getargspec_no_self' from 'scipy._lib._util' (/home/rajat/workspace/body/lib/python3.7/site-packages/scipy/_lib/_util.py)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ImportError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3337, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3434, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/posixpath.py\", line 383, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3417, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-9-f1961da6ff9c>\", line 1, in <module>\n",
      "    from white_box_cartoonizer.cartoonize import WB_Cartoonize\n",
      "  File \"/home/rajat/workspace/body/cartoonize/white_box_cartoonizer/cartoonize.py\", line 14, in <module>\n",
      "    import skvideo.io\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/skvideo/__init__.py\", line 3, in <module>\n",
      "    from .utils import check_output, where\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/skvideo/utils/__init__.py\", line 11, in <module>\n",
      "    from .stpyr import SpatialSteerablePyramid, rolling_window\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/skvideo/utils/stpyr.py\", line 3, in <module>\n",
      "    import scipy.signal\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/scipy/signal/__init__.py\", line 301, in <module>\n",
      "    from .filter_design import *\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/scipy/signal/filter_design.py\", line 18, in <module>\n",
      "    from scipy import special, optimize, fft as sp_fft\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/scipy/optimize/__init__.py\", line 389, in <module>\n",
      "    from .optimize import *\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/scipy/optimize/optimize.py\", line 40, in <module>\n",
      "    from scipy._lib._util import getargspec_no_self as _getargspec\n",
      "ImportError: cannot import name 'getargspec_no_self' from 'scipy._lib._util' (/home/rajat/workspace/body/lib/python3.7/site-packages/scipy/_lib/_util.py)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ImportError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3337, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3434, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2922, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3146, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3356, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/rajat/workspace/body/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/posixpath.py\", line 383, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n"
     ]
    }
   ],
   "source": [
    "from white_box_cartoonizer.cartoonize import WB_Cartoonize\n",
    "import cv2\n",
    "from mathplotlib import pyplot as plt\n",
    "img = cv2.imread(\"static/emma.jpg\")\n",
    "plt.imshow(img)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
